// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWSxmXwUogLBSKIJtbQu0ZBwGOyGNFPoE',
    appId: '1:558966368070:web:1628ae65c59ab73df16747',
    messagingSenderId: '558966368070',
    projectId: 'lost-found-simad',
    authDomain: 'lost-found-simad.firebaseapp.com',
    storageBucket: 'lost-found-simad.firebasestorage.app',
    measurementId: 'G-7YTPBK8QGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVEyTKGnnY5YUvJTmVqvvRSumuWkrZbrY',
    appId: '1:558966368070:android:011e782559162dd7f16747',
    messagingSenderId: '558966368070',
    projectId: 'lost-found-simad',
    storageBucket: 'lost-found-simad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvwpC7CF1VpT0pu3kmK_piFM-Ixffg1Y',
    appId: '1:558966368070:ios:884702b39fe084eef16747',
    messagingSenderId: '558966368070',
    projectId: 'lost-found-simad',
    storageBucket: 'lost-found-simad.firebasestorage.app',
    iosBundleId: 'com.example.lostNFoundSimad',
  );
}
